### ISSUE TITLE
Integrate prettier, eslint, husky, commitlint and lint-staged

### ISSUE THREAD

**Issue by omeralpi** [omeralpi/shadcn-phone-input#51]
### TODOs:
- [ ] Update Prettier and ESLint configurations to match Vercel Style Guide.
- [ ] Add Commitlint to enforce commit message rules.
- [ ] Set up Husky to enforce pre-commit hooks.
- [ ] Make sure Husky;
  - [ ] Runs Commitlint to check commit messages.
  - [ ] Triggers lint-staged to run Prettier and ESLint on staged files.

### Acceptance Criteria:
- [ ] Linting and formatting follow Shadcn UI's standards.
- [ ] Commit messages follow these allowed types: `build, ci, docs, feat, fix, perf, refactor, revert, style, test, and release.`
- [ ] Code must be properly formatted to commit.
